### ISSUE TITLE
suppress Region Poly display?

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/public-digital-library#12]
When displaying Places, such as [rnam gling rdzong](http://library.bdrc.io/show/bdr:G2171), it would probably be best to suppress the display of the ``bdo:placeRegionPoly`` - perhaps just a note that there is one. It's not particularly informative otherwise.

**Comment by berger-n** [comment]
yes you are right
I already noticed that
this Region Poly information should not be displayed as is
