### ISSUE TITLE
order of properties

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/public-digital-library#18]
the order of properties when displayed in a page (such as [this one](http://library.bdrc.io/show/bdr:WCBC2237)) varies from one browser to another... the order should be consistent and controlled in some (currently unspecified) way

**Comment by berger-n** [comment]
(some) properties are explicitly sorted [here](https://github.com/BuddhistDigitalResourceCenter/public-digital-library/blob/b183afb1f269a0e433c6b6c08c8710d088805801/src/components/ResourceViewer.js#L121)
just added alphabetical sort to the remaining properties
see eg http://library.bdrc.io/show/bdr:W23703

meanwhile I found this strange empty string `prefLabel` & `workTitle` fields in http://purl.bdrc.io/resource/W0RKA0652.ttl :
![image](https://user-images.githubusercontent.com/33383857/46352563-66de4880-c65a-11e8-89cd-bb9019a4b4d5.png)
should I report it somewhere ?
seems to be part of a bunch of *not-labeled-at-all* resources: http://library.bdrc.io/show/bdr:W0RKT0651
yet http://library.bdrc.io/show/bdr:W0RKT0650 or http://library.bdrc.io/show/bdr:W0RKT0653 are ok

**Comment by eroux** [comment]
The empty title you found is an interesting edge case of [rKTs-migration](https://github.com/BuddhistDigitalResourceCenter/rKTs-migration), can you report it there?
