### ISSUE TITLE
need to add DTS and ALA-LC to Language dropdown

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/public-digital-library#20]
We need to add:

    Tibetan (DTS)
    Tibetan (ALA-LC)

to the language background with the appropriate language tags for queries:

    bo-x-dts
    bo-alalc97

**Comment by berger-n** [comment]
done
(I also added a textfield to input other languages tag when needed)

**Comment by xristy** [comment]
Nice! Thanks
