### ISSUE TITLE
adjustments in the language select

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/public-digital-library#21]
Instead of having three Chinese Hanzi possibilities, there should be only one, named "Chinese (Hanzi)" that would map to `zh-Hant`.

There should be also a `Sanskrit (Lenient)` mapping to `sa-x-ndia`

**Comment by berger-n** [comment]
I am not sure to understand what you mean
see eg http://library.bdrc.io/show/bdr:G9GBX420325000 it uses zh-hans mainly
ok to add `sa-x-ndia` good idea
BTW I could not find the page where these codes are detailed ?

**Comment by eroux** [comment]
oh, sorry, I just meant the language dropdown on the search page, not the preferred language page (the two sets should be slightly different).

What I think there should be in the dropdown list is:

- Chinese (Hanzi) -> zh-hant
- Chinese (Pinyin) -> zh-latn-pinyin
- Tibetan -> bo
- Tibetan (EWTS) -> bo-x-ewts
- Tibetan (DTS) -> bo-x-dts
- Sanskrit (Rom.) -> sa-x-iast
- Sanskrit (Deva) -> sa-deva
- English
- Pali (Rom.) -> pi-x-iast
- Other

**Comment by xristy** [comment]
The list above should include:

- Tibetan (ALA-LC) -> ``bo-alalc97``

as currently, I.e., please don't remove it.

Also I suggest that we just have

- Chinese -> ``zh-hans``

like we do for Tibetan.

The reason we don't need to discriminate between ``zh-hans`` and ``zh-hant`` for the search is because these two are handled back in Fuseki without any particular distinction but it seems to be true that much of the data is tagged ``zh-hans``

**Comment by eroux** [comment]
Thanks, can you rename `Chinese (Simplified)` into `Chinese` in the dropdown please?

**Comment by berger-n** [comment]
no problem, but how to label "zh" then ?

**Comment by berger-n** [comment]
I mean:

![image](https://user-images.githubusercontent.com/33383857/46870925-49fefd80-ce30-11e8-8d6f-6a678b6c2634.png)

**Comment by eroux** [comment]
Well, I'm affraid we need to make a distinction on the labels of the preferred languages and the labels of the dropdown, these are of two different natures

**Comment by berger-n** [comment]
indeed
obviously

**Comment by berger-n** [comment]
done

![image](https://user-images.githubusercontent.com/33383857/46879909-8722ba00-ce47-11e8-9aab-0888432da691.png)

**Comment by eroux** [comment]
thanks!
