### ISSUE TITLE
there could be highlighting in titles

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/public-digital-library#25]
When I query:

    klong rab ʾbyams

There are 39 Texts and 2 Works. The titles, in particular of Works, with matches in them could have the matches highlighted. As it is there is highlighting in the content of the Texts.

**Comment by berger-n** [comment]
you can try [klong rab 'byams](http://library.bdrc.io/search?q=%22klong%20rab%20%27byams%22&lg=bo-x-ewts&t=Any)
(this a particular case due to the ʾ, I'll fix it)

**Comment by xristy** [comment]
Much nicer!

**Comment by eroux** [comment]
I think this could be closed, @xristy ?
