### ISSUE TITLE
Chinese (Pinyin) not working

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/public-digital-library#26]
Selecting ``Chinese (Pinyin)`` and entering the query: `` jīng`` or ``dān zhū``, for example, produces nothing even though a simple sparql query produces sensible results:

    select ?s ?lbl
    where {
      (?s ?sc ?lbl) text:query (skos:prefLabel "\"jīng\""@zh-latn-pinyin)
    } limit 10

Other queries with Tibetan (EWTS), Tibetan (ALA-LC) and Chinese (Traditional) continue to work. The Chinese (Pinyin) seemed to work once.

Here's screen shot:

<img width="1400" alt="screen shot 2018-10-11 at 12 49 57 pm" src="https://user-images.githubusercontent.com/3542294/46824010-57938500-cd55-11e8-8809-95282b2d4b40.png">

**Comment by berger-n** [comment]
opening the error console, switching to Network tab and reloading:
![image](https://user-images.githubusercontent.com/33383857/46829391-f9d75b00-cd9d-11e8-84d5-255d5819774b.png)
![image](https://user-images.githubusercontent.com/33383857/46829405-06f44a00-cd9e-11e8-9841-14420940fc2f.png)

query http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=zh-latn-pinyin&I_LIM=500&L_NAME=%22j%C4%ABng%22 fails
looks related to https://github.com/BuddhistDigitalResourceCenter/lds-pdi/issues/93

**Comment by xristy** [comment]
it does look like this may be a symptom of the other.

If fixing [lds-pdi #93](https://github.com/BuddhistDigitalResourceCenter/lds-pdi/issues/102) fixes this then this issue can be closed as well.

**Comment by berger-n** [comment]
(I'm afraid your link doesn't point to https://github.com/BuddhistDigitalResourceCenter/lds-pdi/issues/93 but lds-pdi#102)

**Comment by xristy** [comment]
I fixed the link but the prblem still remains ;-)

**Comment by eroux** [comment]
fixed in lds-pdi
