### ISSUE TITLE
search fails with "Cross-Origin Request Blocked"

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/public-digital-library#29]
I try the query ``manju`` after setting the _Language_ to ``sa-x-ndia`` (verify in address bar):

<img width="982" alt="screen shot 2018-10-12 at 4 40 21 pm" src="https://user-images.githubusercontent.com/3542294/46895343-956bd880-ce3d-11e8-9ed3-ccb8fe0dd14a.png">

I see a return to the Sample queries and the spinner running on the refine panel - see above.

The FF network shows:

<img width="1475" alt="screen shot 2018-10-12 at 4 38 19 pm" src="https://user-images.githubusercontent.com/3542294/46895418-e5e33600-ce3d-11e8-9e15-bc9d4792f57e.png">

I know that the basic query:

    select ?s ?lbl
    where {
      (?s ?sc ?lbl) text:query (rdfs:label "\"manju\""@sa-x-ndia)
    } limit 1000

returns 925 results

**Comment by eroux** [comment]
superseded by https://github.com/BuddhistDigitalResourceCenter/lds-pdi/issues/105
