### ISSUE TITLE
window must be opened much too wide for visibility

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/public-digital-library#3]
The library.bdrc.io landing page requires the browser window to be opened much too wide to view on Safaqri, Chrome, and FireFox. Here's what I see with a nominal 800 px window::

<img width="1147" alt="screen shot 2018-05-22 at 8 34 26 am" src="https://user-images.githubusercontent.com/3542294/40381834-600fbab2-5dc2-11e8-9dde-5ff74f147d48.png">

It should be much more flexible. There's plenty of empty space in the middle.

**Comment by eroux** [comment]
thanks, it's in the to do list (I try to sort it by priority) of the [project](https://github.com/BuddhistDigitalResourceCenter/public-digital-library/projects/1)

**Comment by xristy** [comment]
@berger-n  very nice fix via commit [178e5a7](https://github.com/BuddhistDigitalResourceCenter/public-digital-library/commit/178e5a7369e5e5e8f9b53df3dc2f0081133df0f7)! Thanks

**Comment by berger-n** [comment]
@xristy you're welcome
